import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import "@/Components/Entity/Theme/styles.css";
import ThemeInit from "@/Components/Entity/Theme/Components/ThemeInit";
import { getLayoutTheme } from "@/Components/Entity/Theme/utils.server";
import QueryProvider from "@/lib/query/QueryProvider";
import { Toaster } from "@/Components/Shadcn/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = getLayoutTheme(cookieStore);

  return (
    <html className={theme} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen flex-col overflow-hidden antialiased`}
      >
        <ThemeInit />
        <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
          <QueryProvider>{children}</QueryProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
